name: Plan and Deploy Infrastructure

on:
  workflow_call:
    inputs:
      github_environment:
        required: true
        type: string
      include_shared_environment_resources:
        required: true
        type: boolean
      unique_prefix:
        required: true
        type: string
      azure_environment:
        required: true
        type: string
      shared_location:
        required: true
        type: string
      cluster_location:
        required: true
        type: string
      cluster_location_acronym:
        required: true
        type: string
      sql_admin_object_id:
        required: true
        type: string
      domain_name:
        required: true
        type: string
      service_principal_id:
        required: true
        type: string
      tenant_id:
        required: true
        type: string
      subscription_id:
        required: true
        type: string
      deployment_enabled:
        required: true
        type: string

jobs:
  plan:
    name: "Planning"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 &&
          chmod +x ./bicep &&
          sudo mv ./bicep /usr/local/bin/bicep &&
          bicep --version

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.service_principal_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Plan Shared Environment Resources
        if: ${{ inputs.include_shared_environment_resources == true }}
        run: bash ./cloud-infrastructure/environment/deploy-environment.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.shared_location }} --plan

      - name: Plan Cluster Resources
        id: deploy_cluster
        run: bash ./cloud-infrastructure/cluster/deploy-cluster.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.cluster_location }} ${{ inputs.cluster_location_acronym }} ${{ inputs.sql_admin_object_id }} ${{ inputs.domain_name }} --plan
  
  deploy:
    name: "Deploying"
    if: ${{ inputs.deployment_enabled == 'true' && github.ref == 'refs/heads/main' }}
    needs: plan
    environment: "${{ inputs.github_environment }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Bicep CLI
        run: |
          curl -Lo bicep https://github.com/Azure/bicep/releases/latest/download/bicep-linux-x64 &&
          chmod +x ./bicep &&
          sudo mv ./bicep /usr/local/bin/bicep &&
          bicep --version

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.service_principal_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Deploy Shared Environment Resources
        if: ${{ inputs.include_shared_environment_resources == true }}
        run: bash ./cloud-infrastructure/environment/deploy-environment.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.shared_location }} --apply

      - name: Deploy Cluster Resources
        id: deploy_cluster
        run: bash ./cloud-infrastructure/cluster/deploy-cluster.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.cluster_location }} ${{ inputs.cluster_location_acronym }} ${{ inputs.sql_admin_object_id }} ${{ inputs.domain_name }} --apply

      - name: Refresh Azure Tokens # The previous step may take a while, so we refresh the token to avoid timeouts
        uses: azure/login@v2
        with:
          client-id: ${{ inputs.service_principal_id }}
          tenant-id: ${{ inputs.tenant_id }}
          subscription-id: ${{ inputs.subscription_id }}

      - name: Replace Classic sqlcmd (ODBC) with sqlcmd (GO)
        run: |
          sudo apt-get remove -y mssql-tools &&
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc &&
          sudo add-apt-repository "$(wget -qO- https://packages.microsoft.com/config/ubuntu/22.04/prod.list)" &&
          sudo apt-get update &&
          sudo apt-get install -y sqlcmd

      - name: Grant Database Permissions
        run: |
          bash ./cloud-infrastructure/cluster/grant-database-permissions.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.cluster_location_acronym }} 'account-management' ${{ steps.deploy_cluster.outputs.ACCOUNT_MANAGEMENT_IDENTITY_CLIENT_ID }}
          bash ./cloud-infrastructure/cluster/grant-database-permissions.sh ${{ inputs.unique_prefix }} ${{ inputs.azure_environment }} ${{ inputs.cluster_location_acronym }} 'back-office' ${{ steps.deploy_cluster.outputs.BACK_OFFICE_IDENTITY_CLIENT_ID }}
